### ISSUE TITLE
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by ufxpri** [shjo-april/sanghyunjo#1]
# issue
pillow 9.5.0 를 초과하는 버전에서 'getsize' 의 속성 오류 발생

# error log
```bash
Traceback (most recent call last):
  File "/workspace/test_code.py", line 308, in <module>
    main()
  File "/workspace/test_code.py", line 299, in main
    stats = process_video(video_path, fire_model, leak_model, person_model, args)
  File "/workspace/test_code.py", line 157, in process_video
    annotated_frame = person_model.draw(draw_person_input, person_event.collapse)
  File "/workspace/core/models.py", line 287, in draw
    return YOLOv9.draw(data.image.copy(), output)
  File "/workspace/core/networks.py", line 112, in draw
    shjo.draw_text(demo, *box.text, centering=False)
  File "/opt/conda/lib/python3.10/site-packages/sanghyunjo/cv_utils.py", line 151, in draw_text
    tw, th = font.getsize(text)
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```

# related
https://github.com/tensorflow/models/issues/11040

# solution
1. pillow 버전 9.5.0 이하로 명시
2. 'getsize' 속성 사용 안함

**Comment by shjo-april** [comment]
아래 두 가지 수정하여 해결했습니다 :) 87c3857bb91de300962cb213cac777f6ad984706

1. `pip install sanghyunjo --upgrade` 설치 시 필요한 라이브러리 자동 다운로드 받도록 업데이트
* https://github.com/shjo-april/sanghyunjo/blob/master/setup.py#L12-L18
2. pillow 9.5.0 이하 버전이 아닌, 최신 버전에 호환될 수 있도록 코드 수정
* https://github.com/shjo-april/sanghyunjo/blob/master/sanghyunjo/cv_utils.py#L436-L438
